version: '3.8'

services:
  redis:
    image: redis:7-alpine
    # This is required to stay in RAM only.
    command: redis-server --save "" --appendonly no
    # Additionally, you can set a size limit. See link below on how to customise.
    # https://redis.io/docs/manual/eviction/
    # --maxmemory 1gb --maxmemory-policy allkeys-lru

  app:
    image: cupcakearmy/cryptgeon:latest
    depends_on:
      - redis

  proxy:
    image: nginx:alpine
    depends_on:
      - app
    volumes:
      - ./nginx-plain.conf:/etc/nginx/conf.d/default.conf
      # Or with tls
      # - ./nginx-tls.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
