name: Publish Docker image on AWS ECR Public

on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
env:
  REPOSITORY_NAME: cryptgeon
  AWS_ALIAS: r9h8b0z6

jobs:
  AWS:
    name: AWS ECR public
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ARN }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push the image to Amazon ECR
        id: build-image
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/$AWS_ALIAS
          docker build -t public.ecr.aws/$AWS_ALIAS/$REPOSITORY_NAME:latest .
          docker push public.ecr.aws/$AWS_ALIAS/$REPOSITORY_NAME:latest
